version: 2.1

executors:
  cloud-sdk:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/work
  gatsby:
    docker:
      - image: circleci/node:15
    working_directory: ~/work
  git-crypt:
    docker:
      - image: xueshanf/docker-git-crypt
    working_directory: ~/work


jobs:
  encrypt:
    executor: git-crypt
    steps:
      - checkout:
          path: repo
      - run:
          name: Encrypt repo
          command: |
            echo $GIT_CRYPT_KEY | base64 -d > ~/keyfile
            cd ./repo
            git-crypt unlock ~/keyfile
      - persist_to_workspace:
          root: ~/work
          paths:
            - repo
               
  deploy-django:
    executor: cloud-sdk
    steps:
      - attach_workspace:
          at: ~/work
      - run:
          name: Copy across app.yaml config
          working_directory: repo/apps/django_server
          command: |
            echo "export DJANGO_ENV=$CIRCLE_BRANCH" >> $BASH_ENV
            source $BASH_ENV
            python3 ./app.yaml.py
      - run:
          name: Make migrations
          working_directory: repo/apps/django_server
          command: |
            apt-get -y install python3-venv
            python3 -m venv venv
            source ./venv/bin/activate
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py migrate
      - run:
          name: Set up gcloud config
          working_directory: repo/apps/django_server
          command: |
            echo $GCLOUD_KEY | base64 -di | gcloud auth activate-service-account ${GCLOUD_ACC} --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT}
            gcloud --quiet config set compute/zone ${GCLOUD_ZONE}
      - run:
          name: Deploying to App Engine
          working_directory: repo/apps/django_server
          command: gcloud app deploy app.yaml
          
  deploy-gatsby:
    executor: gatsby
    steps:
      - attach_workspace:
          at: ~/work
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "repo/apps/gatsby-app/package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: repo/apps/gatsby-app
      - save_cache:
          key: v1-npm-deps-{{ checksum "repo/apps/gatsby-app/package-lock.json" }}
          paths:
            - ./repo/apps/gatsby-app/node_modules
      - run:
          name: Gatsby Build
          command: |
            echo "export GATSBY_ENV=$CIRCLE_BRANCH" >> $BASH_ENV
            source $BASH_ENV
            npm run build
          working_directory: repo/apps/gatsby-app
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
          working_directory: repo/apps/gatsby-app
          
            
  

workflows:
  deploy:
    jobs:
      - encrypt:
          filters:
            branches:
              only:
                - master
                - staging
                - development
      - deploy-django:
          name: deploy-django
          requires:
            - encrypt
          filters:
            branches:
              only:
                - master
                - staging
                - development
      - deploy-gatsby:
          name: deploy-gatsby
          requires:
            - encrypt
          filters:
            branches:
              only: master
